### ISSUE TITLE
Fails if nounset bash option set

### ISSUE THREAD

**Issue by yeeplusplus** [codehearts/shpy#12]
If the `nounset` bash option is set, spies will fail due to checking of undefined variables.

Example:

```bash
#!/usr/bin/env bash

set -o nounset

testNoUnset() {
  createSpy some_cmd

  some_cmd
}

. ../shpy/shpy
. ../shpy/shpy-shunit2
. ./shunit2
```

Output:
```
testNoUnset
../shpy/shpy: line 153: _shpy_inited: unbound variable
ASSERT:unknown failure encountered running a test

Ran 1 test.

FAILED (failures=1)
```

**Comment by yeeplusplus** [comment]
This also fails:

`uut`:
```bash
set -o nounset

run_uut() {
  some_cmd
}
```

`test_file`:
```bash
#!/usr/bin/env bash

testNoUnsetSource() {
  createSpy some_cmd

  . ./uut

  run_uut
}

. ../shpy/shpy
. ../shpy/shpy-shunit2
. ./shunit2
```

Output:
```
testNoUnsetSource
../shpy/shpy: line 267: output: unbound variable
ASSERT:unknown failure encountered running a test

Ran 1 test.

FAILED (failures=1)
```

**Comment by codehearts** [comment]
Nice catch! Looks like `_shpyInit`, `_shpySpyPrintOutput`, and `_shpySpyPrintErrorOutput` all check for the existence of variables by testing `-n "$var"`

The POSIX-compliant convention seems to be `-n ${var+is_set}`, as defined here: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

This is the relevant entry from their table explaining how this works (I actually didn't know this until now)


| | parameter Set and Not Null | parameter Set But Null | parameter Unset |
| -- | -- | -- | -- |
| ${parameter+word} | substitute word | substitute word | substitute null |

I'll get a little PR together to resolve this ✨
