### ISSUE TITLE
More 'undefined' vars checks

### ISSUE THREAD

**Issue by yeeplusplus** [codehearts/shpy#17]
There are three more instances where undefined variables aren't checked in a way that works with the `nounset` flag

Example (dummy_test):
```bash
testDummy() {
  set -o nounset
  cleanupSpies
}
```

Output:
```
# dummy_test: 147: eval: _shpy_spies_dir: parameter not set
```

The other two instances involve `createSpy`: if a return value is passed via `-r`, and if no spy name is passed

**Comment by codehearts** [comment]
I think the remaining undefined variables have been weeded out, is it alright if I close this or do you want to take a second look at this?

**Comment by yeeplusplus** [comment]
You can close it.  Sorry I haven't been as available as I thought I would be.

**Comment by codehearts** [comment]
It's ok, I really appreciate your contributions and I'm sorry for trampling over your last PR! You actually revealed that shpy wasn't working under some of the shells it claimed to support, and it's motivated me to pay more attention to this project
