### ISSUE TITLE
Infamous trailing spaces in wc util on mac

### ISSUE THREAD

**Issue by OperationalFallacy** [codehearts/shpy#45]
Hi,

Thanks for an amazing framework, it helped me refactoring tons of shell scripts that overwise were hopeless.

I run into small issues while developing on Mac. The wc util has a nasty behavior on Macs where its return contains leading spaces, as described here https://stackoverflow.com/questions/30927590/wc-on-osx-return-includes-spaces

This makes the output of `_shpyGetDirectoryContentsCount` function incorrect, which breaks counts when there are multiple spy calls.

I can submit PR, but I'd like to know if this is something worth fixing. I guess people may run into this if they develop on Macs? 

Thanks!

**Comment by codehearts** [comment]
I'm happy to support macOS! That might be the BSD version of the utility as opposed to the GNU one, so this could help users on those OS as well

If you get a PR up I'll take a peek at it as soon as I can, or I can take a crack at it if you're busy!

**Comment by OperationalFallacy** [comment]
Cool, thanks 
I’ll submit PR
