### ISSUE TITLE
Question about nested functions calls

### ISSUE THREAD

**Issue by OperationalFallacy** [codehearts/shpy#47]
I was looking how to refactor ol’ scripts without too much rewriting and have functions there tested separately. The easiest way was to source target script (with some logic to prevent it running everything) and then do usual spy/asserts for each function.

However, if functionA calls functionB which calls functionC - then spy for functionB is ignored because I think bash first calls sourced functions and then one in PATH.

Workaround is to remove all nested functions with ‘unset -f functionB’ inside each test.

I wonder if that’s something framework can handle, maybe with a flag?

**Comment by codehearts** [comment]
That's a really good point, shpy is creating executables and adding the to `PATH` but those are superseded by local function definitions. I think this could be resolved if `_shpyCreateSpyExecutable` defined a local function or alias with the same name which calls `$spy_file`
